### DISCUSSION TITLE
Loading colorscheme (tokyonight.nvim)

### DISCUSSION THREAD

**Discussion by Rasmus-Bertell** [lumen-oss/rocks.nvim#212] [Q&A] [answered]
I'm trying to switch to rocks.nvim from lazy.nvim but I'm having trouble loading colorscheme.

My rocks.toml file is 

```toml
[rocks]

[plugins]
"rocks.nvim" = "2.17.0"
"oil.nvim" = "2.7.0"
"tokyonight.nvim" = "3.0.1"
```

and in the end of my init.lua I have

```lua
require('tokyonight').setup({ style='night' })
vim.cmd.colorscheme('tokyonight')
```

but I get an error that the colorscheme is not found, however running `:colorscheme tokyonight-night` works.

Is there something I'm missing?

Edit:

I also tried with rocks-config.nvim, but it had the same problem. I could run `require('tokyonight').setup()` but right after it `vim.cmd.colorscheme('tokyonight')` didn't work.
