### DISCUSSION TITLE
How to silence message about deprecated rocks.packadd?

### DISCUSSION THREAD

**Discussion by salkin-mada** [lumen-oss/rocks.nvim#310] [Q&A] [answered]
Hi team! My neovim life has been going thru Plug, Packer and Lazy. I have been using Rocks for 48 hours now, and it is so so so sweet. `Rocks.nvim = QOL`
But one thing is interfering, almost intruding :-)
I am constantly getting the following message when I start up neovim. And sometimes also when adding new buffers.
```
rocks.packadd is deprecated, use Neovim's built-in 'packadd' instead.                                                             
Feature will be removed in rocks.nvim 3.0.0   
```
How can this be silenced?

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the nice words 😄 
We recently made rocks.nvim compatible with neovim's built-in `:packadd` and deprecated `:Rocks packadd` and `require("rocks").packadd` (https://github.com/nvim-neorocks/rocks.nvim/pull/292).

Are you calling one of those in your config somewhere?

**Reply by salkin-mada** [reply]
Hi!

Nope not intentionally. At least in my `~/.config/nvim` I only use a `vim.cmd[[packadd termdebug]]`. Maybe one of the plugins I am using..?
```toml
[rocks]

[plugins]
"rocks.nvim" = "2.26.0"
neorg = "8.4.0"
"rocks-git.nvim" = "1.4.0"
"rocks-config.nvim" = "1.5.0"

"rocks-treesitter.nvim" = "scm"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
tree-sitter-vim = "scm"
tree-sitter-supercollider = "scm"
tree-sitter-vimdoc = "scm"

fzf-lua = "0.0.1246"
alpha-nvim = { git = "goolord/alpha-nvim" }
scnvim = { git = "davidgranstrom/scnvim" }
luasnip = "2.3.0"
nvim-cmp = "0.0.1"
nvim-lspconfig = "0.1.7"
"lspkind.nvim" = "scm"
tree-sitter-markdown = "scm"
cmp-path = "scm"
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-nvim-lsp = "scm"
cmp_luasnip = "scm"
"which-key.nvim"= "1.6.0"
"comment.nvim" = "0.8.0"
"neoscroll.nvim"= "scm"
# "sweetie.nvim" = "3.1.0" # colorscheme
"toggleterm.nvim" = "2.11.0"
"lualine.nvim" = "scm"
"color-picker.nvim" = "scm"
tree-sitter-html = "scm"
"kanagawa.nvim" = "scm"
"overseer.nvim" = "1.3.1"
"dressing.nvim" = "2.2.0"

[plugins."nvim-colorizer.lua"]
git = "NvChad/nvim-colorizer.lua"

[config]
plugins_dir = "plugins/"
auto_setup = false
colorscheme = "kanagawa"

[treesitter]
auto_install = "false"
auto_highlight = "all"
```
But I did go to `~/.local/share/nvim` and did a _Fzflua live_grep_ search for `*.packadd`. And the only files returned was from within Rocks.nvim it self. 
Like line # 13 in `rocks/init.lua`
`vim.deprecate("rocks.packadd", "Neovim's built-in 'packadd'", "3.0.0", "rocks.nvim")`..
Hmm.. but that's the deprecation so hehe not the trigger i guess 😄
And in `rocks/share/lua/5.1/rocks/commands.lua` line # 218-227 I see:
```lua
packadd = {
	impl = function(args, opts)
		if #args ~= 1 then
			vim.notify("Rocks packadd: Called without required rock argument.", vim.log.levels.ERROR)
			return
		end
		local rock_name = args[1]
		require("rocks").packadd(rock_name, { bang = opts.bang })
	end,
}
```
But If its not a small notification BUG on Rocks.nvim's behalf. Then yeah I guess somewhere `Rocks.packadd` or `req'rocks'.packadd()` is being called..
