### DISCUSSION TITLE
:Rocks log missing error

### DISCUSSION THREAD

**Discussion by sahinf** [lumen-oss/rocks.nvim#321] [Q&A] [answered]
Howdy again, 

I ran `:Rocks sync` and got the following error
![image](https://github.com/nvim-neorocks/rocks.nvim/assets/6597168/7b1cc430-8768-43a6-8778-02b00c4c092f)
(Zen-Mode is actually installed and works okay. All my sync attempts get that error)

Followed instructions and ran `:Rocks log`
```text
[start][2024-05-07 11:50:59] rocks.nvim logging initiated
error | 2024-05-07 11:51:12 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:348 | sync completed with errors! run ':rocks log' for details.
error | 2024-05-07 11:51:32 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:348 | sync completed with errors! run ':rocks log' for details.
error | 2024-05-07 11:51:56 | ...share/nvim/rocks/rocks_rtp/lua/rocks/operations/init.lua:348 | sync completed with errors! run ':rocks log' for details.
```

Now I'm stuck recursively running `:Rocks log` trying to find those details :(

**Comment by mrcjkb** [comment]
Hey :wave: 

What does the entry in your rocks.toml look like?

`:Rocks log` primarily provides details about when a luarocks error occurs. In this case, it's rocks.nvim failing to parse the entry in your rocks.toml.

**Comment by sahinf** [comment]
```toml
[plugins]
#"image.nvim" = "1.2.0"
"tmux.nvim" = "scm"
"rocks-config.nvim" = "1.5.0"
nvim-surround = "2.1.5"
"twilight.nvim"= "1.0.0"
"vim-nightfly-colors"= "scm"
neorg = "8.4.0"
nvim-lspconfig = "0.1.7"
tree-sitter-lua = "scm"
"rocks-treesitter.nvim" = "scm"
tree-sitter-vimdoc = "scm"
"rocks-git.nvim" = "1.5.0"
"cmp-nvim-lsp" = "scm"
"telescope.nvim" = "scm"
"oil.nvim" = "2.8.0"
"zen-mode.nvim" = "scm"
nvim-possession = "0.0.13"
"rocks.nvim" = "2.27.1"
tree-sitter-markdown = "scm"
"lualine.nvim" = "scm"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

# LuaRocks nvim-cmp is outdated use github source
[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.zen-mode.config]
plugins = { tmux = { enabled = true },alacritty = { enabled = true, font = "20" } }

[config]
plugins_dir = "plugins/"
auto_setup = true
```

**Comment by mrcjkb** [comment]
The problem is that you have:

```toml
"zen-mode.nvim" = "scm"
```

but also

```toml
[plugins.zen-mode.config]
```

which are two different entries (with different keys).

If you change it to

```toml
[plugins."zen-mode.nvim"]
version = "scm"
config = { plugins = { tmux = { enabled = true },alacritty = { enabled = true, font = "20" } } }
```

it won't throw any errors.
