### DISCUSSION TITLE
Error while calling lua chunk: TOML parse error

### DISCUSSION THREAD

**Discussion by craigmac** [lumen-oss/rocks.nvim#364] [Q&A] [answered]
When trying to use in my rocks.toml:

```toml
[plugins.nvim-surround.config]
options = {}
```

I get the following stack traceback:

```
Error detected while processing /Users/craigmaceachern/.local/share/nvim/
rocks/lib/luarocks/rocks-5.1/rocks.nvim/2.29.1-1/plugin/rocks.lua:
E5113: Error while calling lua chunk: TOML parse error at line 56, column
 1
   |
56 | [plugins.nvim-surround.config]
   | ^
invalid table header
dotted key `plugins.nvim-surround` attempted to extend non-table type (st
ring)

stack traceback:
        [C]: in function 'parse_as_tbl'
        ...share/nvim/rocks/share/lua/5.1/rocks/config/internal.lua:54: i
n function 'get_rocks_toml'
        ...share/nvim/rocks/share/lua/5.1/rocks/config/internal.lua:74: i
n function 'get_user_rocks'
        .../luarocks/rocks-5.1/rocks.nvim/2.29.1-1/plugin/rocks.lua:57: i
n main chunk
```

I've also tried to use `[plugins."nvim-surround".config]` in case it was the `-` character, but that didn't work. Right below it I have:

```toml
[plugins.flit.confg]
options = {}
```

Which works. Any ideas?

**Comment by mrcjkb** [comment, marked as answer]
🤔 that looks like it should parse fine. 
Could you please post your whole rocks.toml?

Maybe you have 

```toml
[plugins]
nvim-surround = "<version>"
```

somewhere?
If so, you should change it to

```toml
[plugins.nvim-surround]
version = "<version>"

[plugins.nvim-surround.config]
options = {}
```

**Reply by craigmac** [reply]
That worked, thanks! Why does it not work the way I had it before, is it a TOML thing?

**Reply by mrcjkb** [reply]
The entry `nvim-surround = "<version>"` makes `nvim-surround` a string.

```toml
[plugins.nvim-surround]
version = "<version>"
```
makes it a table. 

It has to be a table if you want to index it.
