### DISCUSSION TITLE
dependencies

### DISCUSSION THREAD

**Discussion by Pakrohk** [lumen-oss/rocks.nvim#501] [Q&A]
In general, how can I determine the dependencies of a package, most of the prerequisites are due to my configuration type, which are prerequisites of another package, and in the default state, they may not be prerequisites of that package, this confused me a little.

```toml
[plugins]
"telescope.nvim" = "scm"
[plugins.telescope]
config = "plugins.ui.telescope.config"
[plugins.telescope.dependencies]
"plenary.nvim" = "scm" 
telescope_fzf_native = { git = "nvim-telescope/telescope-fzf-native.nvim" , build = "make" }
telescope_ui_select = { git = "nvim-telescope/telescope-ui-select.nvim" }
```

I am going to fully transfer nvpak from lazy.nvim to Rocks.nvim and this is a need to be able to manage dependencies.
